version: "3"

services:
  client:
    build: ./client
    environment:
      - PORT=$CLIENT_PORT
    ports:
      - $CLIENT_PORT:$CLIENT_PORT
    volumes:
      - ./client:/home/node/app

  server:
    build: ./server
    depends_on:
      - db
    environment:
      - PORT=$SERVER_PORT
      - MONGO_HOST=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_USER=$MONGO_USER
      - MONGO_PASSWORD=$MONGO_PASSWORD
    networks:
      - backend
    ports:
      - $SERVER_PORT:$SERVER_PORT
    volumes:
      - ./server:/home/node/app

  db:
    image: mongo:4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    networks:
      - backend
    volumes:
      - spackle-mongo:/data/db

networks:
  backend:

volumes:
  spackle-mongo:
